hello:
	python C:\Users\abhi0\Desktop\Data-Structures-and-Algorithms\Data-structures\LinkedList\Linked_list.py
	python C:\Users\abhi0\Desktop\Data-Structures-and-Algorithms\Data-structures\LinkedList\DoublyLinkedList.py